import { NextPage, NextPageContext, GetStaticProps } from "next";
import Link from 'next/link'
import Head from 'next/head'

// eslint-disable-next-line @typescript-eslint/no-empty-interface
type SSGProps = {
    message: string
}

const SSG: NextPage<SSGProps> =  (props) => {

    const { message } = props
    return (
        <div>
            <Head>
                <title>Static Site Generation</title>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <p>
                    This page was generated by SSG when building it.
                </p>
                <p> {message}</p>
            </main>
            <Link href='/ssr'>
            <a>Go to SSR</a>
            </Link>
        </div>

    )
}

export const getStaticProps: GetStaticProps<SSGProps> = async (context) => {
    const timestamp = new Date().toLocaleString()
    const message = `${timestamp} にgetstaticpropsが実行されました`
    console.log(message)
    return {
        props: {
            message,
        },
    }
}

export default SSG