import { GetServerSideProps, NextPage } from "next";
import Link from 'next/link'
import Head from 'next/head'
import Page from './Page'

type SSRProps = {
    message: string
}

const SSR: NextPage<SSRProps> = (props) => {
    const { message } = props

    return (
       <div>
        <Head>
            <title>Create Next App</title>
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <p>
                This page was generated by SSR. Described by the server
            </p>
            <p>{message}</p>
            <Link href='/ssg'>
            <button>Go to SSG</button>
            </Link><br>
            <Page />
        </main>
       </div>
    )
}

export const getServerSideProps: GetServerSideProps<SSRProps> = async (context) => {
    const timestamp = new Date().toLocaleString()
    const message = `${timestamp} getServerSideProps was done`
    console.log(message)

    return{
        props: {
            message,
        },
    }
}

export default SSR
